//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietddh
    {
        public string mactdh { get; set; }
        public string madh { get; set; }
        public Nullable<int> masp { get; set; }
        public Nullable<decimal> giamgia { get; set; }
        public Nullable<int> slmua { get; set; }
        public Nullable<int> dongia { get; set; }
        public Nullable<int> thanhtien { get; set; }
        public string soserial { get; set; }
    }
}
