//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dienthoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dienthoai()
        {
            this.ChitietGiohangs = new HashSet<ChitietGiohang>();
            this.Chitiethdns = new HashSet<Chitiethdn>();
            this.Giabans = new HashSet<Giaban>();
            this.Hoadonnhaps = new HashSet<Hoadonnhap>();
        }
    
        public int masp { get; set; }
        public Nullable<int> madm { get; set; }
        public string tensp { get; set; }
        public Nullable<int> giasp { get; set; }
        public Nullable<int> soluong { get; set; }
        public string manhinh { get; set; }
        public string chip { get; set; }
        public string ram { get; set; }
        public string rom { get; set; }
        public string Camtrc { get; set; }
        public string Camsau { get; set; }
        public string pin { get; set; }
        public string anh { get; set; }
        public string hedh { get; set; }
        public string thesim { get; set; }
        public Nullable<int> giakm { get; set; }
        public string thenho { get; set; }
        public string cambien { get; set; }
        public string gpu { get; set; }
        public string timebh { get; set; }
        public string mancc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietGiohang> ChitietGiohangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiethdn> Chitiethdns { get; set; }
        public virtual Danhmucsp Danhmucsp { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Giaban> Giabans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoadonnhap> Hoadonnhaps { get; set; }
    }
}
