//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donhang
    {
        public string madh { get; set; }
        public string makh { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public Nullable<int> tongtien { get; set; }
        public string noinhan { get; set; }
        public string mand { get; set; }
        public string ghichu { get; set; }
        public string hovaten { get; set; }
        public string diachikhachhang { get; set; }
        public string diachigiaohang { get; set; }
        public string sodienthoaikhachhang { get; set; }
        public string sdtnguoinhan { get; set; }
        public string socmtndkh { get; set; }
        public string socmtndnguoinhan { get; set; }
        public string taikhoan { get; set; }
        public Nullable<int> tongsotien { get; set; }
        public Nullable<int> tienvat { get; set; }
        public Nullable<int> trangthaidonhang { get; set; }
    
        public virtual Khachhang Khachhang { get; set; }
        public virtual Ngdung Ngdung { get; set; }
    }
}
