//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giohang
    {
        public string makh { get; set; }
        public Nullable<double> tongtien { get; set; }
        public string id { get; set; }
        public string tensp { get; set; }
        public string dongia { get; set; }
        public string soluong { get; set; }
        public string thanhtien { get; set; }
        public string anh { get; set; }
    
        public virtual Khachhang Khachhang { get; set; }
    }
}
