//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadonnhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoadonnhap()
        {
            this.Chitiethdns = new HashSet<Chitiethdn>();
        }
    
        public int mahdn { get; set; }
        public string mancc { get; set; }
        public int masp { get; set; }
        public string mand { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> gianhap { get; set; }
        public Nullable<double> Thanhtien { get; set; }
        public string NgayNhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiethdn> Chitiethdns { get; set; }
        public virtual Dienthoai Dienthoai { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual Ngdung Ngdung { get; set; }
    }
}
