//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLPhone1Entities : DbContext
    {
        public QLPhone1Entities()
            : base("name=QLPhone1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chitietddh> Chitietddhs { get; set; }
        public virtual DbSet<ChitietGiohang> ChitietGiohangs { get; set; }
        public virtual DbSet<Chitiethdn> Chitiethdns { get; set; }
        public virtual DbSet<Danhmucsp> Danhmucsps { get; set; }
        public virtual DbSet<Dienthoai> Dienthoais { get; set; }
        public virtual DbSet<Donhang> Donhangs { get; set; }
        public virtual DbSet<Giaban> Giabans { get; set; }
        public virtual DbSet<Giohang> Giohangs { get; set; }
        public virtual DbSet<Hoadonnhap> Hoadonnhaps { get; set; }
        public virtual DbSet<Khachhang> Khachhangs { get; set; }
        public virtual DbSet<LoaiTinTuc> LoaiTinTucs { get; set; }
        public virtual DbSet<Ngdung> Ngdungs { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TinTuc> TinTucs { get; set; }
    }
}
